# Install 19 Oracle   
 - set_fact: inst_cmd="{{ oracle_database_oracle_home }}/runInstaller  -silent -responseFile {{ oracle_database_distr }}/db{{ oracle_database_release | replace('.','') }}.rsp -waitForCompletion -ignorePrereqFailure"

 - name: command for runInstaller 19
   debug: var=inst_cmd

 - name: check file size sqlplus
   stat:
     path: "{{ oracle_database_oracle_home }}/bin/sqlplus"
   register: size_sqlplus  

 - name: Install RDBMS Oracle 19
   shell: "{{ inst_cmd }}"
   args: #creates: "{{ oracle_database_oracle_home }}/bin/sqlplus"
     executable: /bin/bash
     chdir: "{{ oracle_database_oracle_home }}"
   become: yes
   become_user: oracle
   register: shell_result
   when: "size_sqlplus.stat.size==0"
   failed_when: 
     - "'Successfully Setup Software.' not in shell_result.stdout_lines"
     - "'Successfully Setup Software with warning(s).' not in shell_result.stdout_lines"
     - "'skipped' not in shell_result.stdout_lines"

 - name: installation results 19
   debug:
     var: shell_result

 - name: run post-installation scripts as root
   shell: "{{item}}"
   with_items:
     - "{{ oracle_database_inventory_location }}/orainstRoot.sh"
     - "{{ oracle_database_oracle_home }}/root.sh"
   become: yes
   when: shell_result.changed